# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DRAM/DRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DRAM || ORIG_REF_NAME==DRAM}]

# IP: bd/DRAM/ip/DRAM_blk_mem_gen_0_0/DRAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==DRAM_blk_mem_gen_0_0}]

# XDC: bd/DRAM/DRAM_ooc.xdc
