# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/GitHub/Image_Downsampling_Processor/Processor.cache/wt [current_project]
set_property parent.project_path D:/GitHub/Image_Downsampling_Processor/Processor.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
add_files c:/Users/ASUS/Desktop/notebooks/Processor_Design_Resources/rom.coe
read_verilog -library xil_defaultlib {
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/AC_Reg.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/ALU.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/A_Bus.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/Baud_gen.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/Control_Unit.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/bd/DRAM/hdl/DRAM_wrapper.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/IR.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/IRAM.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/MAR.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/Memory_Control.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/R16_bit.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/R16_bit_inc.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/R8_bit.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/Rx.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/addr_mux.v
  D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/new/Processor.v
}
add_files D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/bd/DRAM/DRAM.bd
set_property used_in_implementation false [get_files -all d:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/bd/DRAM/ip/DRAM_blk_mem_gen_0_0/DRAM_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/bd/DRAM/DRAM_ooc.xdc]
set_property is_locked true [get_files D:/GitHub/Image_Downsampling_Processor/Processor.srcs/sources_1/bd/DRAM/DRAM.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top processor -part xc7z010clg400-1


write_checkpoint -force -noxdef processor.dcp

catch { report_utilization -file processor_utilization_synth.rpt -pb processor_utilization_synth.pb }
